apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: tomsblog
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: tomsblog
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-image-updater
        email: flux@tomirgang.de
      messageTemplate: |
        chore: update blog-content image to {{range .Changed.Changes}}{{.NewValue}}{{end}}
    push:
      branch: main
  update:
    path: ./infra/k8s
    strategy: Setters
